# Generated by Django 3.2.16 on 2022-11-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('bandera', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mundial.equipo'),
        ),
    ]
