# Generated by Django 4.1.3 on 2022-11-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ('-id',), 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
    ]
