# Generated by Django 3.2.16 on 2022-11-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0002_alter_jugador_options'),
        ('mundial', '0002_auto_20221128_1246'),
    ]

    operations = [
    ]
