# Generated by Django 3.2.16 on 2022-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0003_merge_20221128_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('Mediocampista', 'Mediocampista'), ('Arquero', 'Arquero'), ('Defensor', 'Defensor'), ('Delantero', 'Delantero')], max_length=60),
        ),
    ]
